
export interface Question {
  id: number;
  question: string;
  options: string[];
  correctAnswer: string;
  explanation: string;
  sourceQuote: string; // New field for grounding
  refinedInsight?: string;
  topic?: string;
}

export type ExamMode = 'PRACTICE' | 'MOCK' | 'STUDY_GUIDE';
export type QuestionOrder = 'SEQUENTIAL' | 'RANDOM';
export type AnswerFormat = 'MCQ_4' | 'MCQ_5' | 'TF' | 'AUTO';

export interface DocumentSource {
  text?: string;
  fileData?: {
    data: string; // base64
    mimeType: string;
  };
}

export interface ExamConfig {
  mode: ExamMode;
  durationMinutes: number;
  totalQuestions: number;
  model: string;
  questionOrder: QuestionOrder;
  answerFormat: AnswerFormat;
  contentRange?: string;
  examName?: string;
}

export interface UserAnswer {
  questionId: number;
  selectedOption: string;
  isCorrect: boolean;
  timeSpent: number;
}

export interface ExamResult {
  id: string;
  score: number;
  totalQuestions: number;
  answers: UserAnswer[];
  questions: Question[];
  startTime: number;
  endTime: number;
  mode: ExamMode;
  model: string;
  customName?: string;
  examSessionId?: string; // Link to ExamSession (Level 2)
  retakeOf?: string; // ID of the original exam result this is a retake of
}

export interface PerformanceAnalysis {
  overallFeedback: string;
  strengths: string[];
  areasForImprovement: string[];
  commonMistakes: string[];
}

export enum AppState {
  HOME = 'HOME',
  SETUP = 'SETUP',
  LOADING = 'LOADING',
  EXAM = 'EXAM',
  RESULTS = 'RESULTS'
}

// Three-layer architecture for question preservation
export interface OriginalQuestion extends Question {
  // Exactly as generated by AI - never modified
  _locked: true;
}

export interface OptionMapping {
  questionId: number;
  // Maps display index to original index: displayIndex -> originalIndex
  // e.g., { 0: 2, 1: 0, 2: 3, 3: 1 } means display option 0 is original option 2
  indexMap: Record<number, number>;
}

export interface ExamSession {
  id: string;
  originalQuestions: OriginalQuestion[]; // Deep-cloned, never modified
  optionMappings: OptionMapping[]; // Shuffle tracking per question
  documentHash: string; // Hash of source document
  createdAt: number;
  examConfig?: ExamConfig; // Optional: for context
  retakeOf?: string; // Session ID this is a retake of (for Level 2)
}

// Level 3: Difficulty Tracking
export type DifficultyLevel = 'EASY' | 'MEDIUM' | 'HARD';

export interface QuestionPerformance {
  questionId: number;
  topic?: string;
  // Tracks correct/incorrect attempts across all exams
  correctCount: number;
  totalAttempts: number;
  // Calculated difficulty based on success rate
  difficulty: DifficultyLevel;
  // Last attempt date for freshness
  lastAttemptDate: number;
  // Attempts where question was skipped
  skippedCount: number;
}

export interface DifficultyMetrics {
  // Aggregated performance by difficulty level
  easyQuestions: QuestionPerformance[]; // >= 75% correct
  mediumQuestions: QuestionPerformance[]; // 50-74% correct
  hardQuestions: QuestionPerformance[]; // < 50% correct
}

export interface UserPerformanceProfile {
  documentHash: string;
  // Performance by question ID
  questionMetrics: Map<number, QuestionPerformance>;
  // Overall metrics
  totalAttempts: number;
  averageScore: number;
  lastUpdated: number;
  // Difficulty distribution
  difficultyDistribution: DifficultyMetrics;
}