
/**
 * Interaction style of a question.
 * - 'single'   : one correct option (classic MCQ — the historical default).
 * - 'multiple' : "Choose two / three" — user must select an exact set of options.
 * - 'matching' : drag-drop style — left prompts each paired to a right answer.
 * - 'dropdown' : hotspot style — one or more blanks, each a dropdown of options.
 * Absent/undefined is treated as 'single' for backward compatibility.
 */
export type QuestionType = 'single' | 'multiple' | 'matching' | 'dropdown';

/** A single left→right pairing for a 'matching' question. */
export interface MatchPair {
  prompt: string; // left-side item
  answer: string; // the correct right-side choice for this prompt
}

/** A single dropdown blank for a 'dropdown' question. */
export interface DropdownBlank {
  label?: string; // optional caption shown next to the dropdown
  options: string[];
  correctAnswer: string; // must equal one of `options`
}

export interface Question {
  id: number;
  /** Absent/undefined ⇒ 'single'. */
  type?: QuestionType;
  question: string;
  options: string[];
  /**
   * Single correct option (kept populated for every type for backward
   * compatibility and legacy code paths; for non-single types it holds a
   * canonical/derived value).
   */
  correctAnswer: string;
  /** 'multiple' — the exact required set of correct options. */
  correctAnswers?: string[];
  /** 'matching' — left→right correct pairings. */
  pairs?: MatchPair[];
  /** 'dropdown' — per-blank options + correct choice. */
  blanks?: DropdownBlank[];
  explanation: string;
  sourceQuote: string; // New field for grounding
  refinedInsight?: string;
  topic?: string;
}

export type ExamMode = 'PRACTICE' | 'MOCK' | 'STUDY_GUIDE';
export type QuestionOrder = 'SEQUENTIAL' | 'RANDOM';
export type AnswerFormat = 'MCQ_4' | 'MCQ_5' | 'TF' | 'AUTO';

export interface DocumentSource {
  text?: string;
  fileData?: {
    data: string; // base64
    mimeType: string;
  };
  /** Optional human-friendly name (e.g. original filename) used by the saved-documents library. */
  name?: string;
}

export interface ExamConfig {
  mode: ExamMode;
  durationMinutes: number;
  totalQuestions: number;
  model: string;
  questionOrder: QuestionOrder;
  answerFormat: AnswerFormat;
  contentRange?: string;
  examName?: string;
  temperature?: number;
}

export type CaseType = 'A' | 'B';

export interface QuestionBank {
  documentHash: string;
  questions: OriginalQuestion[];
  caseType: CaseType;
  poolSize: number;
  createdAt: number;
  modelUsed: string;
}

export interface UserAnswer {
  questionId: number;
  /** Single selection (back-compat). For non-single types holds a stringified summary. */
  selectedOption: string;
  /** 'multiple' — the set of options the user selected. */
  selectedOptions?: string[];
  /** 'matching' — prompt → chosen answer. */
  matchAnswers?: Record<string, string>;
  /** 'dropdown' — chosen option per blank (index-aligned with Question.blanks). */
  blankAnswers?: string[];
  isCorrect: boolean;
  timeSpent: number;
}

export interface ExamResult {
  id: string;
  score: number;
  totalQuestions: number;
  answers: UserAnswer[];
  questions: Question[];
  startTime: number;
  endTime: number;
  mode: ExamMode;
  model: string;
  customName?: string;
  examSessionId?: string; // Link to ExamSession (Level 2)
  retakeOf?: string; // ID of the original exam result this is a retake of
}

export interface PerformanceAnalysis {
  overallFeedback: string;
  strengths: string[];
  areasForImprovement: string[];
  commonMistakes: string[];
}

export enum AppState {
  HOME = 'HOME',
  SETUP = 'SETUP',
  LOADING = 'LOADING',
  EXAM = 'EXAM',
  RESULTS = 'RESULTS'
}

// Three-layer architecture for question preservation
export interface OriginalQuestion extends Question {
  // Exactly as generated by AI - never modified
  _locked: true;
}

export interface OptionMapping {
  questionId: number;
  // Maps display index to original index: displayIndex -> originalIndex
  // e.g., { 0: 2, 1: 0, 2: 3, 3: 1 } means display option 0 is original option 2
  indexMap: Record<number, number>;
}

export interface ExamSession {
  id: string;
  originalQuestions: OriginalQuestion[]; // Deep-cloned, never modified
  optionMappings: OptionMapping[]; // Shuffle tracking per question
  documentHash: string; // Hash of source document
  createdAt: number;
  examConfig?: ExamConfig; // Optional: for context
  retakeOf?: string; // Session ID this is a retake of (for Level 2)
}

// Level 3: Difficulty Tracking
export type DifficultyLevel = 'EASY' | 'MEDIUM' | 'HARD';

export interface QuestionPerformance {
  questionId: number;
  topic?: string;
  // Tracks correct/incorrect attempts across all exams
  correctCount: number;
  totalAttempts: number;
  // Calculated difficulty based on success rate
  difficulty: DifficultyLevel;
  // Last attempt date for freshness
  lastAttemptDate: number;
  // Attempts where question was skipped
  skippedCount: number;
}

export interface DifficultyMetrics {
  // Aggregated performance by difficulty level
  easyQuestions: QuestionPerformance[]; // >= 75% correct
  mediumQuestions: QuestionPerformance[]; // 50-74% correct
  hardQuestions: QuestionPerformance[]; // < 50% correct
}

export interface UserPerformanceProfile {
  documentHash: string;
  // Performance by question ID
  questionMetrics: Map<number, QuestionPerformance>;
  // Overall metrics
  totalAttempts: number;
  averageScore: number;
  lastUpdated: number;
  // Difficulty distribution
  difficultyDistribution: DifficultyMetrics;
}